config/routes.rb
Rails.application.routes.draw do

resources :selections 

 get "welcome/home"

get "welcome/radioselect" => "welcome#radioselect"

get "welcome/yourbuses" => "welcome#yourbuses"

 
get "welcome/busesarriving" => "welcome#yourbuses_dropdown", as: :busesarriving

 
root "welcome#home"

resources :stations

end

app/models/selection.rb
class Selection < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
       format.html { redirect_to busesarriving_path, notice: 'Selection was successfully created.' }

       format.json { render action: 'show', status: :created, location: @selection }

else

format.html { render action: 'new' }

format.json { render json: @selection.errors, status: :unprocessable_entity }

end

end

end

  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { render :show, status: :ok, location: @selection }
      else
        format.html { render :edit }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:station_name)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
#next two lines required to access the API:

require 'open-uri'

require 'json'

#welcome/home

#just a home/landing-page

def home

end

#action/page where the user will select a station using radio buttons:

def radioselect

#For your ease, an array of all of the rail stations in the MARTA system.

@stations = ["North Springs", "Hamilton E. Holmes", "Lindbergh", "Midtown", "Georgia State", "Reynoldstown/Inman Park", "Dunwoody", "Lenox", "Sandy Springs", "Medical Center", "Doraville", "Chamblee", "Brookhaven/Oglethorpe", "Arts Center", "North Avenue", "Civic Center", "Ashby", "Peachtree Center", "Vine City", "West End", "Airport", "College Park", "East Point", "Philips Arena/CNN Center", "Garnett", "West Lake", "Bankhead", "Oakland City", "Lakewood/Ft. McPherson", "King Memorial", "Avondale", "East Lake", "Kensington", "Decatur", "Indian Creek", "Edgewood/Candler Park", "Inman Park/Reynoldstown", "Buckhead"]

#Let's save them alphabetically - will be easier to find a particular station when choosing from a list.

@stations = @stations.sort_by{|item| item.downcase}

end

  def yourbuses
  @station = params[:station]

  @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)

  hash_and_msg_generator(@results, @station)
end

#find this method in the Application Helper!

  # def yourbuses_dropdown
  	#page where the coming buses will be displayed, after the dropdown menu choice

def yourbuses_dropdown

yourstation = Selection.last

@selection = yourstation.station_name

@results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)

hash_and_msg_generator(@results, @selection)

#find this method in the Application Helper!

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

def hash_and_msg_generator(results, station)

@message = ""

@buses = {}

results.each do |result|

	if result["TIMEPOINT"].include? station

@buses[result["ROUTE"]] = result["VEHICLE"]

    end
end

if @buses.count == 0

	@message = "Sorry, it's gonna be a while."

elsif @buses.count == 1

	@message = "These buses will be coming soon:"

else

	@message = "Oops...I think there was a slight error."

end

end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomeradioselect_helper.rb
module WelcomeradioselectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MartaApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">MartaApp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :station_name, Station.all.collect {|station| [ station.name ] } %>
  </div>
  <div class="actions">
    <%= f.submit 'Check for buses!', :class=>'btn submit-button' %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1>Listing selections</h1>

<table>
  <thead>
    <tr>
      <th>Station name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.station_name %></td>
        <td><%= link_to 'Show', selection %></td>
        <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
        <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<h1>New selection</h1>

<%= render 'form' %>

<%= link_to 'Back', selections_path %>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station name:</strong>
  <%= @selection.station_name %>
</p>

<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/welcome/radioselect.html.erb
<h1>Welcome#radioselect</h1>
<p>Find me in app/views/welcome/radioselect.html.erb</p>

<!--

All the CSS classes are optional, and can be found in the application.css file,

which you can copy from GitHub.

-->

<div class="scroll choose-a-station">

<h2 class="orange-text">Choose a Station!</h2>

<p><b>Which MARTA Station Are You At?</b></p>

</div>

<div class="radios">

<!-- Below is the form for Radio Buttons -->

<%= form_tag("/welcome/yourbuses", method: "get") do %>

<%= label_tag(:station, " " ) %>

<br />

<% @stations.each do |s| %>

<!-- We loop through the array and each item (station) is set next to a radio button -->

<%= radio_button_tag(:station, s) %> <%= s %><br />

<% end %>

<%= submit_tag 'Check for buses!', :class=>'btn submit-button' %>

<% end %>

</div>

app/views/welcome/yourbuses.html.erb
<h1>Welcome#yourbuses</h1>
<p>Find me in app/views/welcome/yourbuses.html.erb</p>

<!--

Here we'll see the results of the user's radio-button choice.

-->

 

<h3>

You are at: <%= @station %> Station.

</h3>

 

<div>

<%= @message %>

<!-- Here is the message we set up in the Application Helper -->

</div>

<br />

<% @buses.each do |route, vehicle| %>

<!-- We loop through the hash, printing out keys and values.

If nothing is in the hash, nothing will print out. No harm, no foul. -->

<div>

Route: <%= route %><br />

Vehicle: <%= vehicle %><br />

</div>

<hr />

<% end %>

app/views/welcome/yourbuses_dropdown.html.erb
<h1>Welcome#yourbuses_dropdown</h1>
<p>Find me in app/views/welcome/yourbuses_dropdown.html.erb</p>

<h3>

You are at: <%= @selection %> Station.

</h3>

 

<div>

<%= @message %>

</div>

<br />

<% @buses.each do |route, vehicle| %>

<div>

	Route: <%= route %><br />

Vehicle: <%= vehicle %><br />

</div>

<hr />

<% end %>

app/views/welcomeradioselect/yourbuses.html.erb
<h1>Welcomeradioselect#yourbuses</h1>
<p>Find me in app/views/welcomeradioselect/yourbuses.html.erb</p>

app/views/welcomeradioselect/yourbuses_dropdown.html.erb
<h1>Welcomeradioselect#yourbuses_dropdown</h1>
<p>Find me in app/views/welcomeradioselect/yourbuses_dropdown.html.erb</p>